"""Football-Data.org: standings, recent results and upcoming fixtures for six competitions.

Rate-limit strategy (free tier = 10 requests/minute):
* one request per competition returns the whole season's matches; results AND fixtures are
  filtered locally from that single cached response (10-minute cache);
* standings are cached for 30 minutes and team lists for 24 hours;
* a client-side limiter refuses the 11th call in a minute instead of getting the key blocked.
Nothing here is ever generated by an LLM: every score and table row comes straight from the API.
"""
from __future__ import annotations

import difflib
import logging
import re
import unicodedata
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

from config import require_key, settings
from services.http import MinuteRateLimiter, ServiceError, TTLCache, get_json

log = logging.getLogger(__name__)
BASE_URL = "https://api.football-data.org/v4"
SERVICE = "Football-Data.org"
_cache = TTLCache()
_limiter = MinuteRateLimiter(max_calls=10)

# code -> (English name, Nepali name)
LEAGUES = {
    "PL": ("Premier League", "प्रिमियर लिग"),
    "PD": ("La Liga", "ला लिगा"),
    "BL1": ("Bundesliga", "बुन्डेसलिगा"),
    "SA": ("Serie A", "सेरी ए"),
    "FL1": ("Ligue 1", "लिग १"),
    "CL": ("UEFA Champions League", "युएफा च्याम्पियन्स लिग"),
}
LEAGUE_ALIASES = {
    "premier league": "PL", "english premier league": "PL", "epl": "PL", "pl": "PL", "prem": "PL",
    "प्रिमियर लिग": "PL", "प्रिमियर लीग": "PL",
    "la liga": "PD", "laliga": "PD", "primera division": "PD", "pd": "PD", "spanish league": "PD", "ला लिगा": "PD",
    "bundesliga": "BL1", "bl1": "BL1", "german league": "BL1", "बुन्डेसलिगा": "BL1", "बुन्देसलिगा": "BL1",
    "serie a": "SA", "sa": "SA", "italian league": "SA", "सेरी ए": "SA",
    "ligue 1": "FL1", "ligue one": "FL1", "fl1": "FL1", "french league": "FL1", "लिग १": "FL1", "लिग वान": "FL1",
    "champions league": "CL", "uefa champions league": "CL", "ucl": "CL", "cl": "CL",
    "च्याम्पियन्स लिग": "CL", "च्याम्पियन लिग": "CL",
}
DOMESTIC = ["PL", "PD", "BL1", "SA", "FL1"]


def league_name(code: str, language: str = "en") -> str:
    en, ne = LEAGUES.get(code, (code, code))
    return ne if language == "ne" else en


def resolve_league(name: str | None) -> str | None:
    """Map a free-text league name (English or Nepali) to a Football-Data.org code, else None."""
    if not name:
        return None
    key = name.strip().lower()
    if key.upper() in LEAGUES:
        return key.upper()
    if key in LEAGUE_ALIASES:
        return LEAGUE_ALIASES[key]
    close = difflib.get_close_matches(key, LEAGUE_ALIASES.keys(), n=1, cutoff=0.8)
    return LEAGUE_ALIASES[close[0]] if close else None


@dataclass
class Match:
    utc_date: datetime
    competition: str
    home: str
    away: str
    home_score: int | None
    away_score: int | None
    status: str

    @property
    def finished(self) -> bool:
        return self.status == "FINISHED"

    @property
    def live(self) -> bool:
        return self.status in ("IN_PLAY", "PAUSED", "LIVE")


@dataclass
class StandingRow:
    position: int
    team: str
    played: int
    won: int
    draw: int
    lost: int
    goal_difference: int
    points: int


def _fd_get(path: str, params: dict | None = None):
    key = require_key(settings.football_data_key, "FOOTBALL_DATA_KEY")
    _limiter.acquire(SERVICE)
    return get_json(SERVICE, f"{BASE_URL}{path}", params=params, headers={"X-Auth-Token": key})


def _parse_match(m: dict, competition: str | None = None) -> Match:
    full = (m.get("score") or {}).get("fullTime") or {}
    return Match(
        utc_date=datetime.fromisoformat(m["utcDate"].replace("Z", "+00:00")),
        competition=competition or (m.get("competition") or {}).get("name", ""),
        home=(m.get("homeTeam") or {}).get("name") or "TBD",
        away=(m.get("awayTeam") or {}).get("name") or "TBD",
        home_score=full.get("home"), away_score=full.get("away"),
        status=m.get("status", "UNKNOWN"),
    )


def _season_matches(code: str) -> list[Match]:
    def fetch():
        data = _fd_get(f"/competitions/{code}/matches")
        try:
            return [_parse_match(m, league_name(code)) for m in data["matches"]]
        except (KeyError, TypeError, ValueError) as e:
            raise ServiceError(SERVICE, "returned match data in an unexpected format") from e
    return _cache.get_or_set(("matches", code), 600, fetch)


def get_recent_results(code: str, limit: int = 10) -> list[Match]:
    """Most recent finished (plus any live) matches, newest first."""
    matches = [m for m in _season_matches(code) if m.finished or m.live]
    return sorted(matches, key=lambda m: m.utc_date, reverse=True)[:limit]


def get_upcoming_fixtures(code: str, limit: int = 10) -> list[Match]:
    now = datetime.now(timezone.utc)
    upcoming = [m for m in _season_matches(code)
                if m.status in ("SCHEDULED", "TIMED") and m.utc_date >= now - timedelta(hours=2)]
    return sorted(upcoming, key=lambda m: m.utc_date)[:limit]


def get_standings(code: str) -> list[tuple[str, list[StandingRow]]]:
    """Returns [(group label, rows)]. Leagues have one table; older CL formats had groups."""
    def fetch():
        data = _fd_get(f"/competitions/{code}/standings")
        try:
            tables = [s for s in data["standings"] if s.get("type", "TOTAL") == "TOTAL"]
            out = []
            for s in tables:
                rows = [StandingRow(r["position"], r["team"]["name"], r["playedGames"], r["won"], r["draw"],
                                    r["lost"], r.get("goalDifference", 0), r["points"]) for r in s["table"]]
                label = (s.get("group") or "").replace("_", " ").title()
                out.append((label, rows))
            return out
        except (KeyError, TypeError) as e:
            raise ServiceError(SERVICE, "returned standings in an unexpected format") from e
    return _cache.get_or_set(("standings", code), 1800, fetch)


# ── team lookup ──────────────────────────────────────────────────────────────

def _norm(name: str) -> str:
    name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode().lower()
    name = re.sub(r"\b(fc|cf|afc|sc|ac|ssc|as|club|de|futbol|football)\b", " ", name)
    return re.sub(r"[^a-z0-9 ]", " ", re.sub(r"\s+", " ", name)).strip()


def _competition_teams(code: str) -> list[dict]:
    def fetch():
        data = _fd_get(f"/competitions/{code}/teams")
        return [{"id": t["id"], "names": {_norm(t.get(k) or "") for k in ("name", "shortName", "tla")} - {""},
                 "name": t.get("shortName") or t["name"]} for t in data.get("teams", [])]
    return _cache.get_or_set(("teams", code), 24 * 3600, fetch)


def find_team(team: str, league_code: str | None = None) -> tuple[int, str] | None:
    """Find a team id by fuzzy name, searching the given league first, then the big five."""
    wanted = _norm(team)
    if not wanted:
        return None
    order = ([league_code] if league_code in LEAGUES else []) + [c for c in DOMESTIC if c != league_code]
    for code in order:
        best, best_score = None, 0.0
        for t in _competition_teams(code):
            for n in t["names"]:
                if wanted == n:
                    score = 1.0
                elif len(wanted) >= 4 and wanted in n:      # "barcelona" in "barcelona"
                    score = 0.9
                else:
                    score = difflib.SequenceMatcher(None, wanted, n).ratio()
                if score > best_score:
                    best, best_score = t, score
        if best and best_score >= 0.8:
            return best["id"], best["name"]
    return None


def _team_matches(team_id: int) -> list[Match]:
    def fetch():
        data = _fd_get(f"/teams/{team_id}/matches")
        try:
            return [_parse_match(m) for m in data["matches"]]
        except (KeyError, TypeError, ValueError) as e:
            raise ServiceError(SERVICE, "returned team matches in an unexpected format") from e
    return _cache.get_or_set(("team_matches", team_id), 600, fetch)


def get_team_results(team_id: int, limit: int = 5) -> list[Match]:
    ms = [m for m in _team_matches(team_id) if m.finished or m.live]
    return sorted(ms, key=lambda m: m.utc_date, reverse=True)[:limit]


def get_team_fixtures(team_id: int, limit: int = 5) -> list[Match]:
    now = datetime.now(timezone.utc)
    ms = [m for m in _team_matches(team_id) if m.status in ("SCHEDULED", "TIMED") and m.utc_date >= now]
    return sorted(ms, key=lambda m: m.utc_date)[:limit]
